---
- name: Install nginx
  apt: pkg=nginx state=installed

#- name: Ensure default nginx site is not enabled
#  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Restart nginx
  service: name=nginx state=started enabled=yes
