---
common_packages:
  - autoconf
  - binutils-doc
  - bison
  - build-essential
  - curl
  - daemon
  - flex
  - g++
  - libssl-dev
  - libtool
  - maven2
  - openjdk-6-jdk
  - openjdk-6-jre
  - python-apt
  - python-mysqldb
  - unzip
  - wget
  - zip

ssl_certs_dest_dir: /etc/nginx
