---
# USER

- name: Create group
  group: name=jenkins state=present

- name: Create account
  user: name=jenkins
        home={{ jenkins_home }}
        shell=/bin/bash
        groups=jenkins
        append=yes
        generate_ssh_key=yes
        ssh_key_comment=jenkins@ci.typo3.org

- name: Get public key
  command: cat {{ jenkins_home }}/.ssh/id_rsa.pub
  register: jenkins_public_key
  changed_when: "'ssh-rsa' not in jenkins_public_key.stdout"
  failed_when: "jenkins_public_key.stderr"


# PACKAGE

- name: Create cache folder
  file: path=/var/cache/jenkins owner=jenkins group=jenkins mode=0775 state=directory

- name: Download .deb file
  get_url: url=http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_{{ jenkins_version }}_all.deb
           dest=/var/cache/jenkins/jenkins_{{ jenkins_version }}_all.deb
           mode=0440
  retries: 10

- name: Install .deb file
  command: dpkg --skip-same-version -i jenkins_{{ jenkins_version }}_all.deb chdir=/var/cache/jenkins
  register: jenkins_install_package
  changed_when: "jenkins_install_package.rc != 0"
  failed_when: "jenkins_install_package.rc == 1"

  #- include: service.yml
- include: cli.yml
- include: plugins.yml
  tags: jenkins-plugins
