---
- name: Remove old apt repository
  apt_repository: repo='{{ item }}' state=absent
  with_items:
    - 'deb http://pkg.jenkins-ci.org/debian-stable binary/'
    - 'deb http://pkg.jenkins-ci.org/debian binary/'

- name: Remove old (unstable) repository
  file: path=/etc/apt/sources.list.d/jenkins.list state=absent

- name: Create cache folder
  file: path=/var/cache/jenkins owner=jenkins group=jenkins mode=0775 state=directory

- name: Download .deb file
  get_url: url=http://pkg.jenkins-ci.org/debian-stable/binary/jenkins_{{ jenkins_version }}_all.deb
           dest=/var/cache/jenkins/jenkins_{{ jenkins_version }}_all.deb
           mode=0440
  retries: 10

- name: Install .deb file
  command: dpkg --skip-same-version -i jenkins_{{ jenkins_version }}_all.deb chdir=/var/cache/jenkins
  register: jenkins_install_package
  changed_when: "jenkins_install_package.rc != 0"
  failed_when: "jenkins_install_package.rc == 1"
