---
- name: Build | generate the missing locale and reconfigure locales
  command: locale-gen --purge en_US.UTF-8
  sudo: true
  ignore_errors: true

- name: Build | Reconfigure locales
  command: echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
  sudo: true
  ignore_errors: true
