---
- name: Generate the missing locale and reconfigure locales
  locale_gen: name=en_US.UTF-8 state=present

- name: Reconfigure locales
  lineinfile: dest=/etc/default/locale line={{ item }}
  with_items:
    - LANG="en_US.UTF-8"
    - LANGUAGE="en_US:en"
