---

- name: Build | generate the missing locale and reconfigure locales
  command: locale-gen --purge en_US.UTF-8
  sudo: true
  ignore_errors: true

- name: Build | Reconfigure locales
  command: echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
  sudo: true
  ignore_errors: true

  # TODO ct Still needed? IIRC we only needed them for varnish. And maybe Rubygems like nokogiri?
- name: Build | Make sure essential build/dev tools and compilers are installed/up-to-date
  apt: pkg={{ item }} update_cache=yes
  with_items:
#    - ack
#   - acl
#    - apticron
#    - automake
    - autoconf
    - binutils-doc
    - bison
    - build-essential
    - g++
    - libtool
    - libssl-dev
#    - libwww-perl
#    - update-notifier-common
#    - uuid-dev
    - flex

- name: Common | Make sure some basic tools are installed
  apt: pkg={{ item }} update_cache=yes
  with_items:
    #  This package will install handler for command_not_found that looks up programs not currently installed but available from the repositories.
    #- command-not-found
    - curl
    # - debconf
    # - dmidecode
    # - htop
    # - iftop
    # - iotop
    # - nmap
    # - mosh
    # - pciutils
    # - sysstat
    # - tmux
    # - tshark

  # TODO ct 2014-04-21 Add gerrit keys?
- name: Common | Make sure git is installed
  apt: pkg=git-core

- name: Ruby | Make sure essential ruby packages and compilers are installed/up-to-date
  apt: pkg={{ item }}
  with_items:
    - libxslt-dev
    - libxml2-dev
