---
- name: Create folder
  file: name={{ ssl_certs_dest_dir }} state=directory

- name: Copy over ssl certs
  copy: src={{ item }} dest={{ ssl_certs_dest_dir }} owner=root group=root mode=0600
  with_fileglob:
    - files/ssl/
