---
- name: Download archive
  get_url:
    url: http://dist.sonar.codehaus.org/sonar-{{ sonar_version }}.zip
    dest: /opt/sonar-{{ sonar_version }}.zip
    mode: 0644

- name: Extract archive
  sudo: yes
  unarchive:
    src: /opt/sonar-{{ sonar_version }}.zip
    dest: /opt/
    creates: /opt/sonar-{{ sonar_version }}
    copy: no
  register: new_version

# - name: Fetch old plugins if available
#   shell: ls -1 /opt/sonar/extensions/plugins
#   register: plugin_list
#   ignore_errors: yes

# - name: Copy old extensions
#   command: cp -R /opt/sonar/extensions/plugins /opt/sonar-{{ sonar_version }}/extensions/plugins
#   when: new_version|changed and plugin_list.rc == 0

- name: Apply property files
  copy:
    src: conf
    dest: /opt/sonar-{{ sonar_version }}
    owner: root
    group: root
    mode: 0644

- name: Link current version
  file:
    state: link
    src: /opt/sonar-{{ sonar_version }}
    dest: /opt/sonar

- name: Link init script
  file:
    state: link
    src: /opt/sonar/bin/linux-{{ ansible_architecture | regex_replace('_', '-') }}/sonar.sh
    dest: /etc/init.d/sonar

- include: database.yml
- include: vhost.yml

- name: Enable service
  service: name=sonar state=started enabled=yes
