---
- name: Download archive
  get_url:
    url: http://dist.sonar.codehaus.org/sonar-{{ sonar_version }}.zip
    dest: /opt/sonar-{{ sonar_version }}.zip
    mode: 0644

- name: Extract archive
  unarchive:
    src: /opt/sonar-{{ sonar_version }}.zip
    dest: /opt/sonar-{{ sonar_version }}

- name: Copy old extensions
  command: cp -R /opt/sonar/plugins /opt/sonar-{{ sonar_version }}/plugins

# TODO Sync conf folder
- name: Apply properties
  template:
    src: templates/sonar.properties.j2
    dest: /opt/sonar/conf/sonar.properties

- name: Link current version
  file:
    state: link
    src: /opt/sonar-{{ sonar_version }}
    dest: /opt/sonar

- name: Link init script
  file:
    state: link
    src: /opt/sonar/bin/linux-{{ ansible_architecture }}/sonar.sh
    dest: /etc/init.d/sonar

- name: Enable service
  service: name=sonar state=started enabled=yes

- name: Create vhost
  template:
    src: templates/vhost.j2
    dest: /etc/nginx/sites-enabled/sonar_server.conf
